### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by dcousens** [DerelictOrg/DerelictASSIMP3#6]
Your dub mentions boost,  but you don't have a LICENSE file?

**Comment by p0nce** [comment]
Hello,

This is the same as other DerelictOrg packages, as the licence information is repeated in each `.d` file.
@mdparker I guess this is intentional and WONTFIX?

**Comment by mdparker** [comment]
Yeah, I have no reason to add a LICENSE file. I'm [moving everything over to bindbc](https://github.com/BindBC) anyway, albeit slowly, and am handling the license thing properly there.
